/**
 * Dashboard view generated by the SPA module.
 * TODO: Replace presentation-only values with data from approved API endpoints.
 */

export function render() {
  const view = document.createElement("section");
  view.className = "dashboard-view";
  view.innerHTML = `
    <section class="welcome-banner glass-panel">
      <div><p class="eyebrow">Tuesday, 29 July</p><h2>Good morning, Abel.</h2><p>Here is how your fleet is moving today.</p></div>
      <div class="route-chip"><span class="pulse"></span>All systems operational</div>
    </section>
    <section class="metric-grid" aria-label="Fleet summary">
      <article class="metric-card glass-panel"><span class="metric-icon blue">▣</span><div><p>Total buses</p><strong>24</strong><small>2 in maintenance</small></div></article>
      <article class="metric-card glass-panel"><span class="metric-icon green">◎</span><div><p>On route</p><strong>18</strong><small>75% of fleet active</small></div></article>
      <article class="metric-card glass-panel"><span class="metric-icon amber">◉</span><div><p>Students onboard</p><strong>1,286</strong><small>+8% from yesterday</small></div></article>
      <article class="metric-card glass-panel"><span class="metric-icon violet">◒</span><div><p>Active drivers</p><strong>21</strong><small>3 drivers off duty</small></div></article>
    </section>
    <section class="dashboard-grid">
      <article class="tracking-card glass-panel"><div class="card-heading"><div><p class="eyebrow">Live movement</p><h3>Fleet activity</h3></div><a href="#live_tracking">Open live map →</a></div><div class="map-preview"><div class="map-line line-one"></div><div class="map-line line-two"></div><span class="map-pin pin-one">B12</span><span class="map-pin pin-two">B08</span><span class="map-pin pin-three">B21</span><div class="map-caption"><span class="pulse"></span>18 buses transmitting now</div></div></article>
      <article class="alerts-card glass-panel"><div class="card-heading"><div><p class="eyebrow">Attention needed</p><h3>Operations alerts</h3></div><button type="button">View all</button></div><ul class="alert-list"><li><span class="alert-dot amber"></span><div><strong>Bus 04 is delayed</strong><small>North Campus route · 8 min</small></div><time>Now</time></li><li><span class="alert-dot pink"></span><div><strong>Maintenance check due</strong><small>Bus 17 · Inspection scheduled</small></div><time>10m</time></li><li><span class="alert-dot blue"></span><div><strong>New route request</strong><small>Westfield parent committee</small></div><time>24m</time></li></ul></article>
    </section>
    <section class="bottom-grid"><article class="glass-panel schedule-card"><div class="card-heading"><div><p class="eyebrow">Next departures</p><h3>Today's schedule</h3></div><a href="#routes">Manage routes →</a></div><div class="schedule-row"><b>08:30</b><span class="route-badge">R-01</span><span>Central Station</span><small>Bus 12 · Priya Shah</small></div><div class="schedule-row"><b>08:45</b><span class="route-badge">R-07</span><span>Lakeview</span><small>Bus 08 · Omar Ali</small></div><div class="schedule-row"><b>09:00</b><span class="route-badge">R-12</span><span>Green Park</span><small>Bus 21 · Neha Rao</small></div></article><article class="glass-panel quick-card"><p class="eyebrow">Quick actions</p><h3>Manage your fleet</h3><a href="#buses">Add bus <span>+</span></a><a href="#drivers">Register driver <span>+</span></a><a href="#notifications">Send alert <span>+</span></a></article></section>`;
  return view;
}
